# 日志等级 trace,debug,info,warn,fatal,mark,error,off
log_level: info
# 单条日志长度
log_length: 10000

# 服务器地址
url: http://localhost:2536
# 服务器端口
port: 2536

# 自动更新时间
update_time: 1440
# 自动重启时间
restart_time: 0
# 上线推送通知的冷却时间
online_msg_exp: 1440
# 文件保存时间
file_to_url_time: 1
# 文件访问次数
file_to_url_times:
# 消息类型统计
msg_type_count: false
# 以/开头转为#
/→#: true

# chromium其他路径
chromium_path:
# puppeteer接口地址
puppeteer_ws:
# puppeteer截图超时时间
puppeteer_timeout:

# 米游社接口代理地址，国际服用
proxyAddress: