# 日志等级:trace,debug,info,warn,fatal,mark,error,off
# mark时只显示执行命令，不显示聊天记录
log_level: info
# WebSocket 端口
port: 2536

# chromium其他路径
chromium_path: 
# puppeteer接口地址
puppeteer_ws: 

# 米游社接口代理地址，国际服用
proxyAddress: 

# 上线时给主人推送帮助
online_msg: true
# 上线推送通知的冷却时间
online_msg_exp: 86400